#!/usr/bin/env python

from sys import version_info
from django.utils.crypto import get_random_string

chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
SECRET_KEY = get_random_string(50, chars)

python3 = version_info[0] > 2
def _print3(s):
	print(s)

def _print2(s):
	print(s)

if python3:
	_print3(SECRET_KEY)
else:
	_print2(SECRET_KEY)
